import Head from "next/head";
import Image from "next/image";
import { useTheme } from "next-themes";


export default function Home() {
  const { theme, setTheme } = useTheme();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <button onClick={() => setTheme("light")}>Light Mode</button>
        <button onClick={() => setTheme("dark")}>Dark Mode</button>

        <div>
          <div className="item">item 1</div>
          <div className="item">item 2</div>
          <div className="item">item 3</div>
          <div className="item">item 4</div>
          <div className="item">item 5</div>
          <div className="item">item 6</div>
          <div className="item">item 7</div>
          <div className="item">item 8</div>
          <div className="item">item 9</div>
          <div className="item">item 10</div>
          <div className="item">item 11</div>
          <div className="item">item 12</div>
          <div className="item">item 13</div>
          <div className="item">item 14</div>
          <div className="item">item 15</div>
          <div className="item">item 16</div>
          <div className="item">item 17</div>
          <div className="item">item 18</div>
          <div className="item">item 19</div>
          <div className="item">item 20</div>
        </div>
      </div>
    </>
  );
}
